apiVersion: v1
kind: Secret
metadata:
  name: botcreds
type: Opaque
data:
  SMTPPassword: |
    {{ .Values.smtp.password }}
stringData:
  SMTPUser: "{{ .Values.smtp.user }}"
  SMTPEmail: "{{ .Values.smtp.email }}"
  SMTPAddr: "{{ .Values.smtp.address }}"
  MongoDBConnectionString: "{{ .Values.mongodb.connectionstring }}"
  DiscordToken: "{{ .Values.discord.token }}"
