name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux', 'linuxArm64', 'linuxArm', 'windows','windowsArm64' , 'macOS', 'macOSArm']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: linuxArm64
            os: ubuntu-latest
            target: linux-arm64
          - kind: linuxArm
            os: ubuntu-latest
            target: linux-arm
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: windowsArm64
            os: windows-latest
            target: win-arm64
          - kind: macOS
            os: macos-latest
            target: osx-x64
          - kind: macOSArm
            os: macos-latest
            target: osx-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          
      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="CCSODiscordBot-$tag-${{ matrix.target }}"
          # Build everything
          dotnet publish "CCSODiscordBot" --framework net6.0 --runtime "${{ matrix.target }}" --self-contained true -c Release -o "$release_name"
          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]||[ "${{ matrix.target }}" == "win-arm64" ]||[ "${{ matrix.target }}" == "win-arm" ]; then
            # Pack to zip for Windows
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
          tar czvf "${release_name}.tar.gz" "$release_name"
          fi
          # Delete output directory
          rm -r "$release_name"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "CCSODiscordBot-*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
